### ISSUE TITLE
to_sql?

### ISSUE THREAD

**Issue by apiszcz** [MobilityDB/MobilityDB-python#9]
The Pandas GeoDataframe supports to_sql. Is there an equivalent capability to insert tgeompoint trajectories with the time stamp?
My first review of mobilitydb-python and movingpandas did not locate a capabilty.
movingpandas to_traj_gdf creates a standard geometry for the line string and not a tgeompoint Point(x,y)@timestamp element.
The mobilitydb-python capability does not appear to offer a pandas like capability. 
Current though I'll need to create the tgeompoint string EWKT and insert each row into the postgres/mobilitydb table.
Thank you for any advice.

**Comment by Diviloper** [comment]
I'm closing this issue due to the deprecation of the package in favor of the new [PyMEOS](https://github.com/MobilityDB/PyMEOS) package, which provides a similar collection of classes, but using the MEOS library under the hood.
Although I'm not sure what was the issue here, the new package provides a `to_dataframe` method for temporal points, which may be what you were looking for.
